image: java:8

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/age-agh/age3:node-latest

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - .gradle/wrapper
    - .gradle/caches

test_age:
  stage: test
  script:
    - ./gradlew -PnexusUrl=$DEPLOY_URL -PnexusUsername=$DEPLOY_USERNAME -PnexusPassword=$DEPLOY_PASSWORD test
  tags:
    - java

deploy_age_snapshot:
  stage: deploy
  only:
    - develop
  script:
    - ./gradlew -PnexusUrl=$DEPLOY_URL -PnexusUsername=$DEPLOY_USERNAME -PnexusPassword=$DEPLOY_PASSWORD publish
  tags:
    - java

deploy_age_javadocs:
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - 'which ssh-agent || ( apk --update add openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  stage: deploy
  only:
    - develop
  script:
    - ./gradlew -PnexusUrl=$DEPLOY_URL -PnexusUsername=$DEPLOY_USERNAME -PnexusPassword=$DEPLOY_PASSWORD alljavadoc
    - scp -r build/docs/javadoc/ $DOCS_URL:dev/
  tags:
    - java

build_core_jar:
  stage: build
  only:
    - develop
  tags:
    - java
  script:
    - ./gradlew -PnexusUrl=$DEPLOY_URL -PnexusUsername=$DEPLOY_USERNAME -PnexusPassword=$DEPLOY_PASSWORD age3-core:shadowJar
  artifacts:
    paths:
      - age3-core/build/libs/age3-core.jar

build_docker:
  stage: deploy
  image: docker:latest
  only:
    - develop
  services:
    - docker:dind
  tags:
    - docker
  dependencies:
    - build_core_jar
  script:
    - cp age3-core/build/libs/age3-core.jar docker/age3-core.jar
    - cd docker
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t registry.gitlab.com/age-agh/age3 .
    - docker push registry.gitlab.com/age-agh/age3
